const questions = [
  // --- 1-15: Everyday Life (ชีวิตประจำวัน) ---
  { "id": 1, "category": "English Vocabulary", "question": "Which word is a fruit?", "options": ["Cabbage", "Apple", "Carrot", "Potato"], "answerIndex": 1 },
  { "id": 2, "category": "English Vocabulary", "question": "I use a _______ to cut paper.", "options": ["Spoon", "Scissors", "Hammer", "Comb"], "answerIndex": 1 },
  { "id": 3, "category": "English Vocabulary", "question": "What time do you usually _______ up in the morning?", "options": ["get", "take", "go", "make"], "answerIndex": 0 },
  { "id": 4, "category": "English Vocabulary", "question": "My mother's sister is my _______.", "options": ["Uncle", "Cousin", "Aunt", "Niece"], "answerIndex": 2 },
  { "id": 5, "category": "English Vocabulary", "question": "We keep milk in the _______.", "options": ["Oven", "Refrigerator", "Wardrobe", "Sink"], "answerIndex": 1 },
  { "id": 6, "category": "English Vocabulary", "question": "Which one is a vehicle?", "options": ["Bicycle", "Building", "Bridge", "Bottle"], "answerIndex": 0 },
  { "id": 7, "category": "English Vocabulary", "question": "A _______ helps sick people in a hospital.", "options": ["Farmer", "Pilot", "Doctor", "Chef"], "answerIndex": 2 },
  { "id": 8, "category": "English Vocabulary", "question": "You wear _______ on your feet.", "options": ["Gloves", "Socks", "Hats", "Shirts"], "answerIndex": 1 },
  { "id": 9, "category": "English Vocabulary", "question": "The opposite of 'Cold' is _______.", "options": ["Freezing", "Cool", "Hot", "Icy"], "answerIndex": 2 },
  { "id": 10, "category": "English Vocabulary", "question": "Which animal can fly?", "options": ["Elephant", "Bird", "Tiger", "Snake"], "answerIndex": 1 },
  { "id": 11, "category": "English Vocabulary", "question": "I feel _______ because I didn't sleep last night.", "options": ["Happy", "Hungry", "Tired", "Thirsty"], "answerIndex": 2 },
  { "id": 12, "category": "English Vocabulary", "question": "We use an _______ when it rains.", "options": ["Uniform", "Umbrella", "Unit", "Union"], "answerIndex": 1 },
  { "id": 13, "category": "English Vocabulary", "question": "The _______ is shining brightly today.", "options": ["Moon", "Star", "Sun", "Cloud"], "answerIndex": 2 },
  { "id": 14, "category": "English Vocabulary", "question": "A person who teaches students is a _______.", "options": ["Lawyer", "Teacher", "Waiter", "Baker"], "answerIndex": 1 },
  { "id": 15, "category": "English Vocabulary", "question": "I need a _______ to write on the paper.", "options": ["Brush", "Pen", "Key", "Eraser"], "answerIndex": 1 },

  // --- 16-30: Law Enforcement & Office (งานตำรวจและสำนักงาน) ---
  { "id": 16, "category": "English Vocabulary", "question": "A _______ is a person who steals from a house.", "options": ["Burglar", "Police", "Victim", "Witness"], "answerIndex": 0 },
  { "id": 17, "category": "English Vocabulary", "question": "The police officer put _______ on the criminal's wrists.", "options": ["Handcuffs", "Rings", "Watches", "Bracelets"], "answerIndex": 0 },
  { "id": 18, "category": "English Vocabulary", "question": "Where do you report a crime?", "options": ["School", "Market", "Police station", "Library"], "answerIndex": 2 },
  { "id": 19, "category": "English Vocabulary", "question": "To _______ means to take someone to the police station for a crime.", "options": ["Help", "Arrest", "Invite", "Follow"], "answerIndex": 1 },
  { "id": 20, "category": "English Vocabulary", "question": "An _______ is something that proves a person is guilty.", "options": ["Evidence", "Example", "Exercise", "Excuse"], "answerIndex": 0 },
  { "id": 21, "category": "English Vocabulary", "question": "The _______ saw the accident and told the police.", "options": ["Criminal", "Witness", "Lawyer", "Driver"], "answerIndex": 1 },
  { "id": 22, "category": "English Vocabulary", "question": "Please _______ this form with your personal details.", "options": ["fill in", "fill out", "fill up", "Both 1 and 2"], "answerIndex": 3 },
  { "id": 23, "category": "English Vocabulary", "question": "A _______ is a place where a trial happens.", "options": ["Prison", "Court", "Bank", "Park"], "answerIndex": 1 },
  { "id": 24, "category": "English Vocabulary", "question": "The police _______ the case to find the truth.", "options": ["investigate", "invent", "invite", "ignore"], "answerIndex": 0 },
  { "id": 25, "category": "English Vocabulary", "question": "A _______ is a document that allows police to search a house.", "options": ["Ticket", "Warrant", "Passport", "Card"], "answerIndex": 1 },
  { "id": 26, "category": "English Vocabulary", "question": "To obey the _______ means to follow the rules of the country.", "options": ["Law", "Leader", "Lesson", "Land"], "answerIndex": 0 },
  { "id": 27, "category": "English Vocabulary", "question": "A _______ is a person who has been harmed by a crime.", "options": ["Suspect", "Victim", "Officer", "Guilty"], "answerIndex": 1 },
  { "id": 28, "category": "English Vocabulary", "question": "Traffic _______ are rules for driving safely.", "options": ["Lights", "Regulations", "Signs", "Police"], "answerIndex": 1 },
  { "id": 29, "category": "English Vocabulary", "question": "The _______ is the leader of a police department.", "options": ["Chief", "Staff", "Member", "Worker"], "answerIndex": 0 },
  { "id": 30, "category": "English Vocabulary", "question": "Don't forget to _______ the documents before sending them.", "options": ["sing", "sign", "site", "side"], "answerIndex": 1 },

  // --- 31-40: Synonyms & Antonyms (คำเหมือนและคำตรงข้าม) ---
  { "id": 31, "category": "English Vocabulary", "question": "What is the synonym of 'Fast'?", "options": ["Slow", "Quick", "Heavy", "Quiet"], "answerIndex": 1 },
  { "id": 32, "category": "English Vocabulary", "question": "What is the synonym of 'Difficult'?", "options": ["Easy", "Simple", "Hard", "Soft"], "answerIndex": 2 },
  { "id": 33, "category": "English Vocabulary", "question": "What is the synonym of 'Happy'?", "options": ["Sad", "Glad", "Angry", "Bored"], "answerIndex": 1 },
  { "id": 34, "category": "English Vocabulary", "question": "What is the synonym of 'Smart'?", "options": ["Stupid", "Intelligent", "Rich", "Tall"], "answerIndex": 1 },
  { "id": 35, "category": "English Vocabulary", "question": "What is the antonym (opposite) of 'Safe'?", "options": ["Secure", "Dangerous", "Quiet", "Clean"], "answerIndex": 1 },
  { "id": 36, "category": "English Vocabulary", "question": "What is the antonym of 'Strong'?", "options": ["Weak", "Power", "Hard", "Fast"], "answerIndex": 0 },
  { "id": 37, "category": "English Vocabulary", "question": "What is the antonym of 'Rich'?", "options": ["Wealthy", "Poor", "Expensive", "Cheap"], "answerIndex": 1 },
  { "id": 38, "category": "English Vocabulary", "question": "What is the antonym of 'Beautiful'?", "options": ["Pretty", "Ugly", "Nice", "Good"], "answerIndex": 1 },
  { "id": 39, "category": "English Vocabulary", "question": "What is the synonym of 'Begin'?", "options": ["Finish", "Stop", "Start", "End"], "answerIndex": 2 },
  { "id": 40, "category": "English Vocabulary", "question": "What is the synonym of 'Large'?", "options": ["Huge", "Small", "Thin", "Short"], "answerIndex": 0 },

  // --- 41-50: Idioms & Expressions (สำนวนภาษา) ---
  { "id": 41, "category": "English Vocabulary", "question": "The idiom 'Piece of cake' means _______.", "options": ["Delicious", "Very easy", "A small gift", "Hungry"], "answerIndex": 1 },
  { "id": 42, "category": "English Vocabulary", "question": "If you are 'under the weather', you feel _______.", "options": ["Hot", "Cold", "Sick", "Happy"], "answerIndex": 2 },
  { "id": 43, "category": "English Vocabulary", "question": "'Once in a blue moon' means _______.", "options": ["Every night", "Very rarely", "Often", "In the morning"], "answerIndex": 1 },
  { "id": 44, "category": "English Vocabulary", "question": "'Break a leg' is a way to say _______.", "options": ["Good luck", "Go away", "Be careful", "Hurry up"], "answerIndex": 0 },
  { "id": 45, "category": "English Vocabulary", "question": "'Give me a hand' means _______.", "options": ["Hold my hand", "Help me", "Give me money", "Shake hands"], "answerIndex": 1 },
  { "id": 46, "category": "English Vocabulary", "question": "'Keep an eye on' means _______.", "options": ["Look at eyes", "Watch carefully", "Close your eyes", "Buy glasses"], "answerIndex": 1 },
  { "id": 47, "category": "English Vocabulary", "question": "'Time flies' means _______.", "options": ["Time is slow", "Time passes quickly", "Buy a clock", "Wait a minute"], "answerIndex": 1 },
  { "id": 48, "category": "English Vocabulary", "question": "'Call it a day' means _______.", "options": ["Start working", "Stop working", "Go to sleep", "Make a call"], "answerIndex": 1 },
  { "id": 49, "category": "English Vocabulary", "question": "'Catch someone's eye' means _______.", "options": ["Attract attention", "Hit someone", "Look for a doctor", "See clearly"], "answerIndex": 0 },
  { "id": 50, "category": "English Vocabulary", "question": "To 'lose your head' means _______.", "options": ["Lose a hat", "Lose control of emotions", "Get a haircut", "Have a headache"], "answerIndex": 1 }
];
